 use POS1
/*================================     Data Preparation and understanding    ==================================*/


/* Q.1 Total Records in Each Table */

select count(*) as Total_Records from [dbo].[Customer]
union all
select count(*) from [dbo].[prod_cat_info]
union all
select count(*) from Transactions

/* Q.2 Total no of transactions that have returned */

select abs(sum(total_amt)) as Returned_Transaction 
from Transactions
where total_amt < 0

/* Q.3 Converting to proper date format */
 Done While importing data
 
/* Q.4 Range of Transaction Data Days, Month, Year in different columns and sorted */

Select Distinct
DATEPART(DAY,tran_date) as D, DATEPART(Month,tran_date) as M, DATEPART(YEAR,tran_date) as Y 
from Transactions
order by DATEPART(YEAR,tran_date), DATEPART(Month,tran_date), DATEPART(DAY,tran_date)

/* Q.5 which Category does the subcategeory "DIY" belongs */

select
prod_cat, prod_subcat
from 
[dbo].[prod_cat_info]
where
prod_subcat = 'DIY'


/*========================================     Data Analysis    ==========================================*/


/* Q.1 Most frequently used channel for transactions */

select
Store_type, count(*) as Cnt 
from
Transactions
Group by Store_type
Order by Count(*) Desc

/* Q.2 Count of Male and Female customers in Database */

select
Gender,count(Gender) as Cnt
from
Customer
where Gender in ('F','M')
Group by Gender

/* Q.3 Maximum no of Customers from which Cities and Count */

select
city_code, count(customer_Id) as Cnt
from
Customer
Group by city_code
Order by count(customer_Id) desc

/* Q.4 How many sub category under "Books" category? */

Select
prod_subcat as sub_cat_under_Books
from
[dbo].[prod_cat_info]
where prod_cat in ('Books')

/* Q.5 Maximum Qty of products ever ordered */

select Top 1
prod_cat_code,sum(Qty) as Sum
from
[dbo].[Transactions]
group by prod_cat_code
order by sum(Qty) desc

/* Q.6 Net total revenue generated in "Electronics" and "Books" category */

select
P.prod_cat, sum(T.total_amt) as Net_Revenue
from 
Transactions as T
left join 
prod_cat_info as P on (P.prod_cat_code = T.prod_cat_code) and (P.prod_sub_cat_code = T.prod_subcat_code)
where P.prod_cat in ('Electronics', 'Books')
group by P.prod_cat
order by P.prod_cat

/* Q.7 Customers >10 Transactions excluding returns */

select
C.customer_Id, count(T.transaction_id) as Cnt
from
Transactions as T
left join
Customer as C on (C.customer_Id = T.cust_id)
where T.total_amt > 0
group by C.customer_Id
Having count(T.transaction_id) >10

/* Q.8 Combined revenue earned from "Electronics" and "Cloting" Category from "Flagship stores" */

select 
T.Store_type, sum(T.total_amt) as Total
from 
Transactions as T
left join
prod_cat_info as P on (P.prod_cat_code = T.prod_cat_code)
where P.prod_cat in ('Electronics', 'Cloting') and T.Store_type = 'Flagship store'
Group by T.Store_type

/* Q.9 Total Revenue for "Male customers in "Electronics" category by Product sub category */

select 
P.prod_subcat, sum(T.total_amt) as Total
from 
Transactions as T
left join
prod_cat_info as P on (P.prod_cat_code = T.prod_cat_code) and (P.prod_sub_cat_code = T.prod_subcat_code)
left join 
Customer as C on (C.customer_Id = T.cust_id) 
where C.Gender = 'M' and P.prod_cat = 'Electronics'
Group by P.prod_subcat

/* Q.10 Percentage of Sales and returns by product sub Category, Top 5 sub Categories based on Sales */


select Top 5
TT.prod_subcat, sum(TT.Sales_Per) as Sales_Percentage
from
(select
P.prod_subcat, (T.total_amt*100/(select sum(total_amt) from Transactions where total_amt >0)) as Sales_Per
from
Transactions as T
Left Join
prod_cat_info as P on (P.prod_cat_code = T.prod_cat_code) and (P.prod_sub_cat_code = T.prod_subcat_code)
Where T.total_amt > 0) as TT
Group by TT.prod_subcat
Order by  Sales_Percentage desc

select Top 5
TT.prod_subcat, sum(TT.Return_Per) as Retuen_Percentage
from
(select 
P.prod_subcat, (T.total_amt*100/ (select sum(total_amt) from Transactions where total_amt < 0)) as Return_Per
from
Transactions as T
Left Join
prod_cat_info as P on (P.prod_cat_code = T.prod_cat_code) and (P.prod_sub_cat_code = T.prod_subcat_code)) as TT
group by TT.prod_subcat
order by Retuen_Percentage


/* Q.11 For all customers aged between 25 to 35 years find what is the net total revenue generated by these consumers
	    in last 30 days of transactions from max transaction date available in the data? */

select
sum(T.total_amt) as Total_Revenue_Generated
from
Transactions as T
left join
Customer as C on (C.customer_Id = T.cust_id)
where datediff(year,C.DOB,GETDATE())>25 and datediff(year,C.DOB,GETDATE())<35 AND T.total_amt > 0 and dateadd(MONTH,-1,(select top 1 tran_date from Transactions order by tran_date desc))<T.tran_date


/* Q.12 Which product category has seen the max value of returns in the last 3 months of transactions? */

select
P.prod_cat, max(T.total_amt) as Max_Return_Amount
from
Transactions as T
Left Join
prod_cat_info as P on (P.prod_cat_code = T.prod_cat_code) and (P.prod_sub_cat_code = T.prod_subcat_code)
where T.total_amt < 0 and dateadd(MONTH,-3,(select top 1 tran_date from Transactions order by tran_date desc))<T.tran_date
group by P.prod_cat


/* Q.13	Which store-type sells the maximum products; by value of sales amount and by quantity sold? */

select Top 1
Store_type ,count(*) as Cnt, sum(Qty) as Sum_Quantity, Sum(total_amt) as Total_Sales
from
Transactions
group by Store_type
order by Sum_Quantity desc, Total_Sales desc

/* Q.14	What are the categories for which average revenue is above the overall average. */

select
*
from 
(select 
P.prod_cat, Avg(T.total_amt) as Average
from
Transactions as T
Left Join
prod_cat_info as P on (P.prod_cat_code = T.prod_cat_code) and (P.prod_sub_cat_code = T.prod_subcat_code)
group by P.prod_cat) TT
where  Average > (Select avg(total_amt) from Transactions)


/* Q.15 Find the average and total revenue by each subcategory for the categories which are among top 5 categories in terms of quantity sold. */

select
P.prod_subcat, Avg(T.total_amt) as Average, Sum(T.total_amt) as Total
from
Transactions as T
Left Join
prod_cat_info as P on (P.prod_cat_code = T.prod_cat_code) and (P.prod_sub_cat_code = T.prod_subcat_code)
where P.prod_cat in (select Top 5
	P.prod_cat
	from
	Transactions as T
	Left Join
	prod_cat_info as P on (P.prod_cat_code = T.prod_cat_code) and (P.prod_sub_cat_code = T.prod_subcat_code)
	group by P.prod_cat
	Order by Sum(T.Qty) desc)
Group by P.prod_subcat